module.exports = {
  roots: ["<rootDir>/src"],
  testMatch: ["**/?(*.)+(spec|test).+(ts|tsx)"],
  setupFilesAfterEnv: ["<rootDir>/setupTests.js"],
  testEnvironment: "jsdom",
  collectCoverage: false,
  coverageReporters: ["text-summary", "html"],
  coverageDirectory: "test-coverage",
  coverageThreshold: {
    global: {
      branches: 0,
      functions: 0,
      lines: 0,
      statements: 0,
    },
  },
  coveragePathIgnorePatterns: ["<rootDir>/src/assets", "node_modules", "stored.*", "index.tsx"],
  moduleNameMapper: {
    "^.+\\.(scss)$": "babel-jest",
    "\\.css$": "identity-obj-proxy",
    "^@apis(.*)$": "<rootDir>/src/apis$1",
    "^@assets(.*)$": "<rootDir>/src/assets$1",
    "^@constants(.*)$": "<rootDir>/src/constants$1",
    "^@components(.*)$": "<rootDir>/src/components$1",
    "^@pages(.*)$": "<rootDir>/src/pages$1",
    "^@enums(.*)$": "<rootDir>/src/enums$1",
    "^@models(.*)$": "<rootDir>/src/models$1",
    "^@routes(.*)$": "<rootDir>/src/routes$1",
    "^@services(.*)$": "<rootDir>/src/services$1",
    "^@styles(.*)$": "<rootDir>/src/styles$1",
    "^@utils(.*)$": "<rootDir>/src/utils$1",
    "^@valueObjects(.*)$": "<rootDir>/src/valueObjects$1",
    "^@views(.*)$": "<rootDir>/src/views$1",
    "\\.(css|less|scss|sss|styl)$": "<rootDir>/node_modules/identity-obj-proxy",
  },
}
