name: CI
on: [push]
jobs:
  standard-checks:
    name: Linting, Testing and Building
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install packages
        run: npm ci

      - name: Lint code with Eslint
        run: npm run lint

      - name: Format code with Prettier
        run: npm run prettier

      - name: Run unit tests with Jest
        run: npm run test

      - name: Build project with Webpack
        run: npm run build

      - name: Performance and Quality Check
        run: npm run lighthouse
